/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spotify.view;

import com.spotify.controller.Controller;
import com.spotify.model.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renea
 */
public class TelaGerenciarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarUsuarios
     */
    Controller controller;
    List<Usuario> usuarios;
    boolean funcao;

    public TelaGerenciarUsuarios(Controller controller) {
        initComponents();
        this.controller = controller;

        this.listarUsuarios();
    }

    private void listarUsuarios() {
        this.usuarios = controller.buscarUsuarios();
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuarios.getModel();
        modelo.setNumRows(0);

        for (Usuario usuario : usuarios) {

            Object[] dados = new Object[]{
                usuario.getId(),
                usuario.getNome(),
                usuario.getLogin(),
                "********",
                usuario.getFuncao(),};

            modelo.addRow(dados);
        }

        jTableUsuarios.setModel(modelo);
    }

    private void atualizarDados(int selectedRow) {
        if (selectedRow == -1) {
            selectedRow = 0;
        }

        int id = (int) jTableUsuarios.getValueAt(selectedRow, 0);
        String nome = (String) jTableUsuarios.getValueAt(selectedRow, 1);
        String email = (String) jTableUsuarios.getValueAt(selectedRow, 2);
        boolean funcao = (boolean) jTableUsuarios.getValueAt(selectedRow, 4);

        jLabelID.setText(Integer.toString(id));
        jTextFieldNome.setText(nome);
        jTextFieldLogin.setText(email);
        if (funcao) {
            jLabelFuncao.setText("Admin");
            jButtonPromover.setText("Rebaixar");
        } else {
            jLabelFuncao.setText("");
            jButtonPromover.setText("Promover");
        }

    }

    private void promoverUsuario(int id, boolean funcaoNova) {
        if (id > 0) {
            boolean result = controller.alterarFuncao(id, !funcaoNova);

            if (result) {
                if (!funcaoNova) {
                    JOptionPane.showMessageDialog(null, "Usuario promovido para Administrador com sucesso!", "Sucesso!", 1);

                } else {
                    JOptionPane.showMessageDialog(null, "Usuario rebaixado para Usuario comums com sucesso!", "Sucesso!", 1);

                }
                listarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao alterar dados, tente novamente mais tarde.", "Erro", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para promover", "Erro", 3);
        }
    }

    private void limparTela() {
        jLabelID.setText("0");
        jLabelFuncao.setText("");
        jTextFieldNome.setText("");
        jTextFieldLogin.setText("");
        jPasswordFieldSenha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonPromover = new javax.swing.JButton();
        jLabelFuncao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAlterar.setText("Salvar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabelNome.setText("Nome");

        jLabel3.setText("Login");

        jTextFieldLogin.setEditable(false);

        jLabel4.setText("Senha");

        jLabelID.setText("0");

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-mail", "Senha", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(4).setMinWidth(40);
            jTableUsuarios.getColumnModel().getColumn(4).setMaxWidth(40);
        }

        jButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCancelar.setText("Voltar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAdicionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdicionar.setText("Limpar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonPromover.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPromover.setText("Promover");
        jButtonPromover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromoverActionPerformed(evt);
            }
        });

        jLabelFuncao.setForeground(new java.awt.Color(0, 204, 0));
        jLabelFuncao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabelNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonPromover, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldLogin)
                    .addComponent(jTextFieldNome)
                    .addComponent(jPasswordFieldSenha))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelID)
                    .addComponent(jLabelFuncao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonPromover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAdicionar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.controller.abrirTela(this, "administrador");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        atualizarDados(jTableUsuarios.getSelectedRow());
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        int id = Integer.parseInt(jLabelID.getText());
        String nome = jTextFieldNome.getText();
        String login = jTextFieldLogin.getText();
        char[] senhaChar = jPasswordFieldSenha.getPassword();
        boolean funcao = jLabelFuncao.getText() == "Admin";

        String senha = "";

        for (char c : senhaChar) {
            senha = senha + c;
        }

        if (nome.isEmpty() || login.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Cadastro", 2);
            return;
        }
        boolean result = true;
        Usuario user = new Usuario(id, nome, funcao, login, senha);
        if (id == 0) {
            result = new Controller().cadastrarUsuario(user);
        } else {
            result = new Controller().alterarDadosUsuario(user);
        }
        if (!senha.isEmpty()) {
            this.controller.alterarSenha(login, senha);

        }
        if (result) {
            JOptionPane.showMessageDialog(null, "Operacao realizada com sucesso!", "Sucesso!", 1);
            listarUsuarios();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao realizar a operação, tente novamente mais tarde.", "Erro", 2);
        }
        limparTela();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPromoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromoverActionPerformed
        int id = Integer.parseInt(jLabelID.getText());
        if (id > 0) {
            boolean funcao = jLabelFuncao.getText() == "Admin";
            promoverUsuario(id, funcao);

        }
        limparTela();
    }//GEN-LAST:event_jButtonPromoverActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jLabelID.getText()) > 0) {
            this.controller.excluirUsuario(jLabelID.getText());
            JOptionPane.showMessageDialog(this, "Usuario Exluido!");
            this.listarUsuarios();
        }
        limparTela();

    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPromover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
