/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spotify.view;

import com.spotify.controller.Controller;
import com.spotify.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author renea
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    Controller controller;
    Usuario usuarioLogado;

    public TelaAdministrador(Controller controller) {
        initComponents();
        this.controller = controller;
        this.usuarioLogado = controller.getUser();

        jLabelNome.setText(usuarioLogado.getNome());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAddMusica = new javax.swing.JButton();
        jButtonAddAlbum = new javax.swing.JButton();
        jButtonAddUsuarios = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNome.setText("Nome");

        jButtonAddMusica.setText("Gerenciar Músicas");
        jButtonAddMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMusicaActionPerformed(evt);
            }
        });

        jButtonAddAlbum.setText("Adicionar Álbum");
        jButtonAddAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAlbumActionPerformed(evt);
            }
        });

        jButtonAddUsuarios.setText("Gerenciar Usuários");
        jButtonAddUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUsuariosActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Voltar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Painel de Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddMusica)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddAlbum)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddUsuarios)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddUsuarios)
                    .addComponent(jButtonAddAlbum)
                    .addComponent(jButtonAddMusica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUsuariosActionPerformed
        this.controller.abrirTela(this, "gerenciarUsuarios");
    }//GEN-LAST:event_jButtonAddUsuariosActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed

        this.controller.exibirHome();
        this.dispose();
        //foi preciso fazer dessa maneira para que nao fosse perdido o estado
        // do player (musica atual, fila, etc)
        // a funcao do controller abrirTela, abre uma nova instancia e a fila é perdida
        // da maneira acima, a tela home fica apenas invisivel.
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAddMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMusicaActionPerformed
        this.controller.abrirTela(this, "adicionarMusica");
    }//GEN-LAST:event_jButtonAddMusicaActionPerformed

    private void jButtonAddAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAlbumActionPerformed
        // TODO add your handling code here:
        String albumNome = JOptionPane.showInputDialog("Nome do Album");
        String artista = JOptionPane.showInputDialog("Nome do Artista");
        boolean result = this.controller.criarAlbum(albumNome, artista);
        if (result) {

            JOptionPane.showMessageDialog(this, "Album criado com sucesso!");

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar albun");

        }

    }//GEN-LAST:event_jButtonAddAlbumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAlbum;
    private javax.swing.JButton jButtonAddMusica;
    private javax.swing.JButton jButtonAddUsuarios;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
