/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spotify.view;

import com.spotify.controller.Controller;
import com.spotify.model.Albun;
import com.spotify.model.Musica;
import com.spotify.model.Playlist;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author renea
 */
public class TelaCadastrarMusica extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarMusica
     */
    Controller controller;

    HashMap<Integer, String> albumIdNome;
    private HashMap<String, Integer> albumNomeId;
    private HashMap<Integer, Integer> albumIdIndex;

    public TelaCadastrarMusica(Controller controller) {

        this.controller = controller;
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);//maximiza a tela

        atualizarMusicas();
        atualizarAlbuns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelArtista = new javax.swing.JLabel();
        jTextFieldArtista = new javax.swing.JTextField();
        jLabelEstilo = new javax.swing.JLabel();
        jTextFieldEstilo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusicas = new javax.swing.JTable();
        jLabelCaminho = new javax.swing.JLabel();
        jTextFieldCaminho = new javax.swing.JTextField();
        jLabelAlbum = new javax.swing.JLabel();
        jComboBoxAlbum = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Música");

        jLabelNome.setText("Nome");

        jLabelArtista.setText("Artista");

        jLabelEstilo.setText("Estilo");

        jTableMusicas.setAutoCreateRowSorter(true);
        jTableMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Artista", "Estilo", "Caminho", "Album"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMusicas);

        jLabelCaminho.setText("Caminho (musica/nomeDaMusica.mp3)");

        jTextFieldCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoActionPerformed(evt);
            }
        });

        jLabelAlbum.setText("Álbum");

        jComboBoxAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCancelar.setText("Voltar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAdicionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdicionar.setText("Adicionar");

        jLabel1.setText("ID:");

        jLabelID.setText("0");

        jButtonLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldArtista, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEstilo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCaminho, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAlbum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCaminho, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEstilo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelArtista, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelID))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstilo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCaminho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAdicionar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void atualizarMusicas() {

        DefaultTableModel tabela = (DefaultTableModel) jTableMusicas.getModel();
        tabela.setNumRows(0);
        List<Musica> musicas = this.controller.buscarMusicas();

        int i = 0;

        for (Musica musica : musicas) {

            tabela.insertRow(i, new Object[]{
                musica.getId(),
                musica.getNome(),
                musica.getArtista(),
                musica.getEstilo(),
                musica.getCaminho(),
                musica.getAlbunId()

            });
            i++;

        }

        jTableMusicas.setModel(tabela);

    }

    private void selecionarLinha(int selectedRow) {
        if (selectedRow < 0) {
            jTableMusicas.setRowSelectionInterval(0, 0);
        }

        String nome = (String) jTableMusicas.getValueAt(selectedRow, 1);
        alterarMusica(nome);
    }

    private void atualizarAlbuns() {
        List<Albun> albuns = this.controller.buscarAlbuns();
        HashMap<Integer, String> albunsIdNome;
        albunsIdNome = new HashMap();
        HashMap<String, Integer> albunsNomeId;
        albunsNomeId = new HashMap();
        HashMap<Integer, Integer> albunsIdIndex;
        albunsIdIndex = new HashMap();

        DefaultComboBoxModel<String> albunsNome = new DefaultComboBoxModel();
        int i = 0;
        for (Albun album : albuns) {
            albunsNomeId.put(album.getNome(), album.getId());
            albunsIdNome.put(album.getId(), album.getNome());
            albunsNome.addElement(album.getNome());
            albunsIdIndex.put(album.getId(), i);
            i++;

        }
        this.albumIdNome = albunsIdNome;
        this.albumNomeId = albunsNomeId;
        this.albumIdIndex = albunsIdIndex;
        jComboBoxAlbum.setModel(albunsNome);

    }

    private void alterarMusica(String nome) {

        Musica musica = this.controller.buscarMusica(nome);
        int id = musica.getId();
        jLabelID.setText(String.valueOf(id));
        jTextFieldNome.setText(musica.getNome());
        jTextFieldArtista.setText(musica.getArtista());
        jTextFieldEstilo.setText(musica.getEstilo());
        jTextFieldCaminho.setText(musica.getCaminho());
        if (musica.getAlbunId() > 0) {
            jComboBoxAlbum.setSelectedIndex(albumIdIndex.get(musica.getAlbunId()));
        } else {
            jComboBoxAlbum.setSelectedIndex(0);
        }

    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.controller.abrirTela(this, "administrador");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMusicasMouseClicked
        // TODO add your handling code here:

        selecionarLinha(jTableMusicas.getSelectedRow());
    }//GEN-LAST:event_jTableMusicasMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        limparTela();

    }//GEN-LAST:event_jButtonLimparActionPerformed
    private void limparTela() {
        jLabelID.setText("0");
        jTextFieldNome.setText("");
        jTextFieldArtista.setText("");
        jTextFieldEstilo.setText("");
        jTextFieldCaminho.setText("");
    }
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

        // criar  funcionalidade criar Musica
        String id = jLabelID.getText();
        String nome = jTextFieldNome.getText();
        String artista = jTextFieldArtista.getText();
        String caminho = jTextFieldCaminho.getText();
        String estilo = jTextFieldEstilo.getText();
        Integer album = albumNomeId.get(jComboBoxAlbum.getSelectedItem());
        
        Musica musica = new Musica(Integer.parseInt(id), nome, artista, caminho, album, estilo);

        if (id.isEmpty() || nome.isEmpty() || artista.isEmpty() || caminho.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        } else {

            if (jLabelID.getText() == "0") {
                //criando nova musica

                this.controller.criarMusica(musica);

            } else {
                this.controller.alterarMusica(musica);
            }
            limparTela();
        }
        atualizarMusicas();

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (jLabelID.getText() != "0") {

            this.controller.excluirMusica(jLabelID.getText());
        }
        atualizarMusicas();
        limparTela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelCaminho;
    private javax.swing.JLabel jLabelEstilo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMusicas;
    private javax.swing.JTextField jTextFieldArtista;
    private javax.swing.JTextField jTextFieldCaminho;
    private javax.swing.JTextField jTextFieldEstilo;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

}
